image: barichello/godot-ci:3.4.2

cache:
  key: import-assets
  paths:
    - .import/

stages:
  - export
  - test

variables:
  EXPORT_NAME: gittest

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

test:
  stage: test
  script:
    - wget -O Gut.zip https://github.com/bitwes/Gut/archive/refs/tags/v7.2.0.zip
    - unzip Gut.zip
    - cp -a Gut-7.2.0/addons/ addons/
    - godot -s addons/gut/gut_cmdln.gd -d --path $PWD -gtest=res://test/unit/test_game.gd -glog=1 -gexit